### ISSUE TITLE
the k may exceeds U256.

### ISSUE THREAD

**Issue by DreamWuGit** [scroll-tech/misc-precompiled-circuit#5]
For the modexp circuit, if we just have x and y in U256 and p in U256 and d<p, then in xy=kp+d the k may not be in U256. For example, take p=2 and x=y close to 2^256, then k will easily exceed U256. So the restriction here that all x, y, k, d are in U256 https://github.com/scroll-tech/misc-precompiled-circuit#ii-constraints-of-xy--kp--d-where-x-y-k-p-in-0-2256-1 . from @huwenqing0606

**Comment by huwenqing0606** [comment]
When $x, y$ are in U256 and $p\geq 2$ is a prime, we must have $k$ in U512 (actually U511). So we can decompose $k$ into more limbs as
$$k=k_0+k_1\cdot 2^{108} + k_2\cdot 2^{216}+ k_3 \cdot 2^{324} + k_4 \cdot 2^{432} \ ,$$
i.e., $k=\overline{\underbrace{\kappa_0\kappa_1...\kappa_{107}}_{k_0}
\underbrace{\kappa_{108}\kappa_{109}...\kappa_{215}}_{k_1}
\underbrace{\kappa_{216}\kappa_{217}...\kappa_{323}}_{k_2}
\underbrace{\kappa_{324}\kappa_{325}...\kappa_{431}}_{k_3}
\underbrace{\kappa_{432}\kappa_{433}...\kappa_{511}}_{k_4}}$ in little-endian form. Then we have

$$\begin{array}{ll}
& k \mod n_1
\\
= & k_0+k_1+k_2\cdot (2^{108}-1+1)^2+k_3\cdot (2^{108}-1+1)^3+k_4\cdot (2^{108}-1+1)^4 \mod n_1
\\
= & k_0+k_1+k_2+k_3+k_4 \mod n_1 \ ,
\end{array}$$
and
$$\begin{array}{ll}
& k \mod n_2
\\
= & k_0+k_1\cdot 2^{108}+\left(k_2+k_3\cdot 2^{108}+k_4\cdot 2^{216}\right) \cdot 2^{216} \mod n_2
\\
= & k_0+k_1\cdot 2^{108} \mod n_2 \ .
\end{array}$$

Further we set $k \mod r =k_5$. So the number in limb representation for $k$ becomes $k=[k_0, k_1, k_2, k_3, k_4, k_5]$. Thus the constraints for $xy=kp+d$ for general $k$ becomes

$$\begin{array}{rcll}
(x_0+x_1+x_2)(y_0+y_1+y_2) & \equiv & (k_0+k_1+k_2+k_3+k_4)(p_0+p_1+p_2) + (d_0+d_1+d_2)  & \mod (2^{108}-1) \ ,
\\
x_0y_0 + (x_1y_0+x_0y_1)\cdot 2^{108} & \equiv & k_0p_0 + (k_1p_0+k_0p_1)\cdot 2^{108} + d_0+d_1\cdot 2^{108} & \mod 2^{216} \ ,
\\
x_3y_3 & \equiv & k_5p_3 + d_3 & \mod r \ ,
\\
d & < & p \ . &
\end{array}$$
As $k \mod n_2$ looks the same for the U256 case with 3 limbs, the second constraint will not change. 
Correct me if I am wrong on this...

**Comment by huwenqing0606** [comment]
Issue explained here https://hackmd.io/6GZz0bFiSXONNSVkRYrkJw?view#Constraint-system-for-x-y-mod-p--d

**Comment by lispc** [comment]
can be closed?

**Comment by huwenqing0606** [comment]
I think so.
