### ISSUE TITLE
BUFMULT =2 may overflow in mod_power216_zero

### ISSUE THREAD

**Issue by DreamWuGit** [scroll-tech/misc-precompiled-circuit#6]

**Comment by huwenqing0606** [comment]
Issue explained here https://hackmd.io/6GZz0bFiSXONNSVkRYrkJw?both#mod_power216_zero-method

**Comment by DreamWuGit** [comment]
fixed in https://github.com/scroll-tech/misc-precompiled-circuit/commit/c96a730a0f84a745a6e46afe02a0a92ef0ad8a84
